<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
 sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>

<?php if(isset($this->statusArr) && empty($this->statusArr)){ ?>
       <div class="nodatatext">
	    <div class="ml-alert-1-info m1-info-set">
		   <div class="style-1-icon info"></div>All Employment Statuses have been added. 
			<a href='<?php echo BASE_URL;?>employmentstatus'>Click here</a>  to view all Employment Statuses
		</div>
	  </div>
<?php } else {?>
<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        <div class="total-form-controller">
		    <div class="new-form-ui clearb">
			  <label class="required">Work Code <img class="tooltip" title="Ex: Full Time, Part Time, Contract" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="division"><?php echo $this->form->workcodename; ?>
				<?php if(isset($this->msgarray['workcodename'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->workcodename->getId(); ?>"><?php echo $this->msgarray['workcodename'];?></span>
				<?php }?>
			</div>	
			</div>
		    <div class="new-form-ui clearb">
			  <label class="required">Work Short Code <img class="tooltip" title="Ex: FT, PT, C" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="division"><?php echo $this->form->workcode; ?></div>
			<?php if(isset($this->msgarray['workcode'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->workcode->getId(); ?>"><?php echo $this->msgarray['workcode'];?></span>
			<?php }?>
			</div>
						
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>employmentstatus';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
</div>
</form>
<?php } 	}	?>