<?php 
if($this->con == 'leavemanagement')
{
  if(!empty($this->uniquedepartmentids))
  {
	   if($this->flag != 'true')
		{
		foreach ($this->uniquedepartmentids as $uniquedepartments) {
				$this->leavemanagementform->department_id->addMultiOption($uniquedepartments['id'],utf8_encode($uniquedepartments['deptname']));
			}
			echo $this->leavemanagementform->department_id;
		}
		else
		{
		echo "nodepartments";
		}
  }
  else
  {
        if($this->flag != 'true')
		{
		foreach ($this->departmentlistArr as $departmentlist) {
				$this->leavemanagementform->department_id->addMultiOption($departmentlist['id'],utf8_encode($departmentlist['deptname']));
			}
			echo $this->leavemanagementform->department_id;
		}
		else
		{
		echo "nodepartments";
		}
  }  

}
else
{
	if($this->flag != 'true')
	{
	foreach ($this->departmentlistArr as $departmentlist) {
			$this->employeeform->department_id->addMultiOption($departmentlist['id'],utf8_encode($departmentlist['deptname']));
		}
		echo $this->employeeform->department_id;
	}

	else
	{
	echo "nodepartments";
	}
}	
	


?> 
 