
<?php 
if (count($this->messages)) {?>
    <div id="dispmsgemp" class="settingssuccess">
        <?php 
            foreach ($this->messages as $message)
            {
                $flag = array();                
                $flag = array_keys($message);
                echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
                echo $message[$flag[0]];
                echo "</div></div>";
            } 
        ?>
    </div>  
    
<?php } 
if($this->dataArray[0]['emptyroles'] == 1)
{
 ?>
     <div class="ml-alert-1-info m1-info-set">
        <div class="style-1-icon info"></div>
            Employees grid will not work as Roles are not added yet.
    </div>
 <?php  } else  {   ?>

<?php
if($this->call != 'ajaxcall')
{
    if(!empty($this->popConfigPermission))
    {
?>
<div>

<!-- For excel Upload -->
<div class="profile-tabs-right-2">
    <div class="flt_right">
        
        <div class="actions_div">

            <span class="uploadbut_exel uploadbutsel flt_left marginfiv" id="upload_custom_div" >Import Employees</span>
            <a target="_blank" href="<?php echo DOMAIN; ?>public/downloads/import_employees.xlsx" class="importformatlink flt_left">Import format</a>
            <a target="_blank" title="Rules to fill in the import employee sheet" href="<?php echo DOMAIN; ?>public/downloads/import_file_rule.pdf" class="importformatlink flt_left">Import rules</a>
            <!--<a target="_blank" href="<?php echo DOMAIN; ?>public/downloads/importguide.pdf" class="importformatlink flt_left">Help</a>-->
            <div id="loaderimgprofile" style="display:none;"><img src="<?php echo DOMAIN; ?>public/media/images/loaderwhite_21X21.gif" style="width:21px; height: 21px; float: none; "/></div>                              
        </div>                                  
    </div>
    <input type="hidden" id="uploadimagepath" name="uploadimagepath" value=""/>
    <input type="hidden" name="emp_excel" value=""/>                                    
                                                                        
</div>
</div>

<span id="error_message"></span>
<div id="upload_error" style="display:none;clear:both;"></div>  
<!-- End excel Upload -->
<?php
    }
}
 

if($this->call == 'ajaxcall'){
    $div = ''; $endDiv = ''; 
} else { 
    $div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
    echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->employeegrid($this->dataArray[0]).$endDiv;
?>
<?php   }   ?>
<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
            $('#dispmsgemp').fadeOut('slow');
        },3000);

<?php } ?>

})
</script>

<?php 
if($this->call != "ajaxcall")
{
    if(!empty($this->popConfigPermission))
    {
?>
<script type="text/javascript">
$(document).ready(function(){
    $.each($('table.grid tbody tr'), function(i,v) {
        var data = $(v).find('td:eq(7) span').html().toLowerCase();
        if(data == 'inactive') {
            $(this).addClass('danger')
        }
    })
});
var btnUpload = $('#upload_custom_div');
new AjaxUpload(btnUpload, {

    action :  base_url+'/employee/uploadexcel',
    name   : 'emp_excel',  //we can rename it 
    dataType: 'json',
    onSubmit: function(file,ext){
    if($("#upload_error").is(":visible"))
     $("#upload_error").hide();
      $("#loaderimgprofile").show();
                                     
    },
    onComplete: function(file, response){
        try
            {
                var result = JSON.parse(response);
                if(result.result == 'success')
                {                        
                    $('#upload_error').show();
                    $("#loaderimgprofile").hide();
                    refreshgrid("employee","No","");
                    $('#upload_error').html('<div  class="ml-alert-1-success"><div style="display:block;"><span class="style-1-icon success"></span>'+result.msg+'</div></div>');
                    setTimeout(function()
                    {
                        $('#upload_error').fadeOut('slow');               
                    },3000);
                }
                else
                {
                    $('#upload_error').show();
                    $("#loaderimgprofile").hide();
                    if(result.msg)
                        $('#upload_error').html('<div  class="ml-alert-1-error"><div style="display:block;"><span class="style-1-icon error"></span>'+result.msg+'</div></div>');
                    else
                        $('#upload_error').html('<div  class="ml-alert-1-error"><div style="display:block;"><span class="style-1-icon error"></span>Please choose different file.</div></div>');
                }
            }
            catch(e)
            {
                $('#upload_error').show();
                $("#loaderimgprofile").hide();
                $('#upload_error').html('<div  class="ml-alert-1-error"><div style="display:block;"><span class="style-1-icon error"></span>Something went wrong, please try again.</div></div>');
            }
    }   
},'json');
</script>
<?php 
}
}
?>

