<?php 
 
$appraisal_id = $this->appraisal_id;
$manager_id = $this->manager_id;
$manager_groups = $this->manager_groups;
$submit_val = $this->submit_val;

if(count($manager_groups) > 0)
{
?>
<?php    foreach($manager_groups as $key =>  $val)
		{
?>	    						    		
        <div class="groupeddiv" id="groupdiv_<?php echo $val['manager_group_id'];?>">
            <div class="groupnamediv"><?php echo $val['group_name'];?></div>
            <div class="empcountdiv">Employees <span class="count"><?php echo $val['empcount'];?></span></div>
            <div class="qscountdiv">Questions <span class="count"><?php echo $val['qscount'];?></span></div>

            <div id="hoverdiv_<?php echo $val['manager_group_id'];?>" class="grphoverclass">
                <ul>	    					                    
                    <li onclick='view_manager_group("<?php echo sapp_Global::_encrypt($val['manager_group_id']);?>","<?php echo sapp_Global::_encrypt($val['group_name']);?>");'>View</li>
                </ul>
            </div>
        </div>

<?php 
		}
} else {
?>
<div class="newgroup_msg managerresponsediv_msg">
		Groups are not configured yet.
</div>
<?php } ?>
<input type="hidden" id="idhid_appraisal_id" value="<?php echo sapp_Global::_encrypt($appraisal_id);?>" />
<input type="hidden" id="idhid_manager_id" value="<?php echo sapp_Global::_encrypt($manager_id);?>" />


