<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Dear <?php echo $this->emp_name;?>,</span>
<?php
if($this->type == 'HR' || $this->type == 'Management' || $this->type == 'Report' || $this->type == 'Approver')
{
?>
    <div style='padding:20px 0 0 0;color:#3b3b3b;'><?php echo $this->requisition_code;?> requisition raised by <?php echo ucfirst($this->raised_name);?> has been <?php echo $this->req_status;?> by <?php echo ucfirst($this->approver_str);?>.</div>								
    <div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url; ?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the requisition details.</div>	
        </div><?php 
}

else if($this->type == 'Raise') 
{
?>
        <div style='padding:20px 0 0 0;color:#3b3b3b;'><?php echo $this->requisition_code;?> requisition raised by you has been <?php echo $this->req_status;?> by <?php echo ($this->raised_name==$this->approver_str)?'you':ucfirst($this->approver_str);?>.</div>
        <div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url; ?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the requisition details.</div>
        </div><?php     
}   
?>