<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
	<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
	&nbsp;
    <div style='padding:20px 0 0 0;color:#3b3b3b;'>
        
        Your identity documents are about to expire on <?php echo $this->expiry_date;?>. Please find the details below:
        <ol>
            <?php 
            foreach($this->docs_arr as $doc)
            {
                echo "<li>".$doc."</li>";
            }
            ?>
        </ol>
    </div>	
    <div style="padding:20px 0 10px 0;">Please <a href="<?php echo BASE_URL; ?>" target="_blank" style="color:#b3512f;">click here</a> to login and update the renewed details.</div>
    &nbsp;
</div>      
	  
