<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
	<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
    <div style='padding:20px 0 0 0;color:#3b3b3b;'>
        Your <?php echo $this->etype;?> is about to expire on <?php echo $this->expiry_date;?> .
    </div>	
    <div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url; ?>" target="_blank" style="color:#b3512f;">click here</a> to login and update the renewed <?php echo $this->etype;?> details.</div>							       
</div>      
	  
