<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
    <div style='padding:20px 0 0 0;color:#3b3b3b;'>
    	Your HRMS account has been made inactive. Your user id is <?php echo $this->user_id;?> and your last login was on <?php echo $this->print_date;?>. 
    </div>
</div>      
	  
