<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
        <div style='padding:20px 0 0 0;color:#3b3b3b;'><?php echo ucfirst($this->candidate_name);?> has been interviewed 
<?php 
 if($this->emp_name == 'HR')
 {
 ?>
        by <?php echo ucfirst($this->reporting_person);?> 
<?php                
 }
?>
        on <?php echo $this->interview_date.", ".$this->interview_time;?> at <?php echo $this->interview_location;?>. 
                  Following is the interview feedback.
                  <div>
			    	<table border="1" style="border-collapse:collapse;">
			    		<tr><td>Feedback</td><td><?php echo $this->interview_feedback;?></td></tr>
			    		<tr><td>Comments</td><td><?php echo $this->interview_comments;?></td></tr>
			    		<tr><td>Round status</td><td><?php echo $this->round_status;?></td></tr>
			    	</table>
                  </div>
                </div>					
			
	        <div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url; ?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the interview details.</div>
	        </div>