<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />	       
    <div style='padding:20px 0 0 0;color:#3b3b3b;'>For <?php echo $this->requisition_code;?> requisition, <?php echo ucfirst($this->candidate_name);?> has been scheduled for <?php echo $this->interview_type;?> round.</div>								
    <div>
    	<table border="1" style="border-collapse:collapse;">
    		<tr><td>Date</td><td><?php echo $this->interview_date;?></td></tr>
    		<tr><td>Time</td><td><?php echo $this->interview_time;?></td></tr>
    		<tr><td>Location</td><td><?php echo $this->interview_location;?></td></tr>
    	</table>
    </div>
    <div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url;?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the requisition details.</div>	
</div>      
   
