<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
	<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
    <div style='padding:20px 0 0 0;color:#3b3b3b;'>
        The leaves of the below employee(s) are pending for approval.
        <div style='padding:10px 0 0 0;'>
        	<table border="1" style="border-collapse:collapse;">
<?php 
            foreach($this->team as $emp_id => $emp_name)
            {
?>
        		<tr><td><?php echo $emp_id;?></td><td><?php echo $emp_name;?></td></tr>
<?php 
            }
?>
        	</table>
        </div>
    </div>	
    <div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url; ?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the leave details.</div>
</div>      
	  
