<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
<?php
if($this->type == 'HR' || $this->type == 'Management' || $this->type == 'Approver')
{
?>
        <div style='padding:20px 0 0 0;color:#3b3b3b;'><?php echo $this->requisition_code.'<b>'.$this->jobtitle.'</b>';?> requisition has been raised by <?php echo ucfirst($this->raised_name);?> is sent to <?php echo ucfirst($this->approver_str);?> for approval.</div>
        <div style='padding:20px 0 10px 0;color:#3b3b3b;'>Please <a href="<?php echo $this->base_url;?>" target='_blank' style="color:#208bbd; text-decoration:none;">click here</a> to check the requisition details.</div>
<?php 
}
else if($this->type == 'Raise') 
{
?>
        <div style='padding:20px 0 0 0;color:#3b3b3b;'><?php echo $this->requisition_code.'<b>'.$this->jobtitle.'</b>';?> requisition has been raised by you is sent to  <?php echo ucfirst($this->approver_str);?> for approval.</div>
        <div style='padding:20px 0 10px 0;color:#3b3b3b;'>Please <a href="<?php echo $this->base_url;?>" target='_blank' style="color:#208bbd; text-decoration:none;">click here</a> to check the requisition details.</div>	
<?php     
}
    
?>	        
</div>      
    
