<?php 
$data = $this->data;
$priority_arr = array(1 => "Low",2 => "Medium",3 => "High");
?>

<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Hi,</span><br />
        <div style='padding:20px 0 0 0;color:#3b3b3b;'>A new request has been raised for your persual.</div>

        <table border="1" >
            <tr>
                <td>Ticket#</td>
                <td><?php echo $data['ticket_number'];?></td>
            </tr>
            <tr>
                <td>Category</td>
                <td><?php echo $data['service_desk_name'];?></td>
            </tr>
            <tr>
                <td>Request Type</td>
                <td><?php echo $data['service_request_name'];?></td>
            </tr>
            <tr>
                <td>Priority</td>
                <td><?php echo $priority_arr[$data['priority']];?></td>
            </tr>
            <tr>
                <td>Description</td>
                <td><?php echo $data['description'];?></td>
            </tr>
            <tr>
                <td>Executor comments</td>
                <td><?php echo $data['executor_comments']==''?"--":$data['executor_comments'];?></td>
            </tr>
            <tr>
                <td>Status</td>
                <td><?php echo $data['status'];?></td>
            </tr>
            <tr>
                <td>Raised by</td>
                <td><?php echo $data['raised_by_name'];?></td>
            </tr>
            <tr>
                <td>Created date</td>
                <td><?php echo sapp_Global::change_date($data['createddate'],'view');?></td>
            </tr>
        </table>
        <div style='padding:20px 0 10px 0;color:#3b3b3b;'>Please <a href="<?php echo $this->base_url;?>" target='_blank' style="color:#208bbd; text-decoration:none;">click here</a> to view the request.</div>
	        
</div>      
    
