<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
    
<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />

<div style='padding:20px 0 0 0;color:#3b3b3b;'><?php echo ucfirst($this->candidate_name);?> has been <?php echo $this->status;?> for the requisition <?php echo $this->requisition_code;?>.</div>

<div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url;?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the requisition details.</div>

</div>      
        