<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php
}else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
			<div class="new-form-ui">
			  <label>Geography Code</label>
			<div class="division"><?php echo $this->form->geographycode; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Default Geography Group</label>
			<div class="division"><?php echo $this->form->defaultGeographyGroup; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Geography Group</label>
			<div class="division"><?php echo $this->form->geographygroupname; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Geography Region</label>
			<div class="division"><?php echo $this->form->geographyregion; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Currency</label>
			<div class="division"><?php echo $this->form->currency; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Geography City</label>
			<div class="division"><?php echo $this->form->geographycityname; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>geographygroup';" type="button" >Cancel</button>
		</div>
</div>   

<?php }?>    