<?php 
 
		if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php 
}else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
<div class="total-form-controller view-form-detail">
			<div class="new-form-ui">
			  <label>Base Currency</label>
			<div class="division"><?php echo $this->form->basecurrency; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Target Currency</label>
			<div class="division loca_state_div"><?php echo $this->form->targetcurrency; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Exchange Rate</label>
			<div class="division"><?php echo $this->form->exchangerate; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Active Start Date </label>
			<div class="division"><?php echo $this->form->start_date; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Active End Date </label>
			<div class="division"><?php echo $this->form->end_date; ?></div>
			</div>
					
			<div class="new-form-ui textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>currencyconverter';" type="button" >Cancel</button>
		</div>
</div>  
<?php } ?>      