<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
        <div class="total-form-controller view-form-detail">
		 	<div class="new-form-ui " style="height:75px;">
			  <label id="injuredDate">Leave Limit</label>
				<div class="division loca_state_div">
				<?php echo $this->form->leave_limit; ?>
				</div>
			</div>
			<!--  <div class="new-form-ui ">
			<label >Used leaves</label>
			<div class="division"><?php //echo $this->form->used_leaves; ?></div>
			</div>-->
			
			<div class="new-form-ui" style="height:75px;">
				  <label>Year</label>
			<div class="division"><?php echo $this->form->alloted_year; ?></div>
			</div>
			
			<div class="clearall usedleaves">
				Leaves Availed : <?php echo $this->form->used_leaves->getValue() ;?>
			</div>
			
			<!--<div class="clearall leavenames">
				<?php 
					if(!empty($this->leaveTypeCount))
					{
						 foreach($this->leaveTypeCount as $key => $leave)
						 {?>
						 <?php echo $leave['leavetype']?> <b>:</b> <?php echo $leave['count'];?>
						 <?php if(sizeof($this->leaveTypeCount) != $key+1){?>,<?php }?>
			   <?php 	 }
					}
				?>
			</div>-->

        <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('empleaves','cancel');" type="button" value="Close"  />
        </div>		

</div>