<?php 
if($this->ermsg =='noedit')
{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>Question is being used in feedforward process, cannot be edited.</div>
<?php 
}
else if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php 
}
else
{
 sapp_Global::generateClientValidations($this->form);
 $request = Zend_Controller_Front::getInstance();
 $actionName = $request->getRequest()->getActionName();
 	if($actionName == 'view')
 	  $viewclass = 'view-form-detail';
 	else
 	  $viewclass = '';  

 	 $departmentArr = array(); 
 	 if(!empty($this->popConfigPermission)) 
 	 {
 	 		if(in_array('feedforwardquestions',$this->popConfigPermission))
 	 		{
 	 			
 	 			$departmentArr['popup_url'] = 'feedforwardquestions/addpopup';
 	 			//$departmentArr['popup_disp_name'] = 'Category';
 	 			//$departmentArr['popup_link_name'] = 'Add category';
 	 		}
 	 }	  
 ?>
<div id="error_message" style="display:none;"></div>
<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        <div class="total-form-controller <?php echo $viewclass;?>">
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'question','', '','required',array());?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'description','', 'textareaheight','',array());?>
					
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<?php if($actionName == 'view'){?>
			<input type="button" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
		<?php }?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>feedforwardquestions';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
	</div>
</form>

	<?php echo sapp_Helper::popup_helper('feedforwardquestions');?>
	
<?php }?>