<?php 

if($this->ermsg != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$data = $this->data;
$id = $this->id;
$previ_data = $this->previ_data;
//$pa_category_name = $this->category_name;
//echo "cat_ID:".$pa_category_id;
//echo "<pre>"; print_r($data); echo "</pre>";
?>
<?php 
if($this->ermsg == '')  { ?>
<div class="requisitions-block">
<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
   <?php
    if($previ_data == 'Yes')
    {
    ?>
    <div class="edit-btn">
        <div class="new-form-ui-submit ">
            <input type="button" class="fltright" onclick="window.location.href='<?php echo BASE_URL; ?>feedforwardquestions';" value="Back" />        
            <?php 
	    if($data['isused'] == 0) 
	    {
	    ?>
		<input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
	    <?php } ?>
        </div>
    </div>
    <?php 
    }
    ?>
   <div class="separetor-heading">Questions</div>
   
 <table width="100%" border="0" cellspacing="0" cellpadding="0" class="requisition-table view-table-data">

<tr  class="req-bg-form">
<td><span class="head_txt">Question </span></td>
<td><?php echo $data['question'];?></td>
</tr>

<tr  class="req-no-form">
<td><span class="head_txt">Description </span></td>
<td><?php echo $data['description'];?></td>
</tr>
   </table>
   </div>
</div>

<?php } }?>