<?php 

if($this->nodata != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$data = $this->data;
$id = $this->id;
$previ_data = $this->previ_data;

?>
<?php 
if($this->ermsg == '')  { ?>
<div class="requisitions-block">
<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
   

   
   <div class="cofig_title" style="margin-left: 0px;padding-top: 0px;">Parameters
   <?php
    if($previ_data == 'Yes')
    {
    ?>
	<div class="new-form-ui-submit "  style="margin-top: 0px; float: right; width: auto; margin-left: 0px; ">
							
						<div class="back-to-page" style="position: relative; float: right; top: 0px;">
							<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>appraisalcategory';" name="Back" value="Back">
						</div>
						<?php if($data['isused'] == 0) { ?>
							<input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
						<?php } ?>
	</div>
    <?php 
    }
    ?>
   </div>
   
 <table width="100%" border="0" cellspacing="0" cellpadding="0" class="requisition-table view-table-data">

<tr class="req-bg-form">
<td width="20%"><span class="head_txt">Parameter </span></td>
<td width="30%"><?php echo $data['category_name'];?></td>
</tr>

<tr  class="req-no-form">
<td><span class="head_txt">Description </span></td>
<td><?php echo $data['description'];?></td>
</tr>
   </table>
   </div>
</div>

<?php } }?>