<?php if (count($this->messages)) {?>
	<div id="dispsyspref" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php } ?>
<span id="error_message"></span>



<?php if(empty($this->dataArray)){?>
	 <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>Identity codes are not yet set.
		<a href='<?php echo BASE_URL;?>identitycodes/add'>Click here</a>&nbsp; to add the identity codes.
	  </div>
<?php }else{?>
<div class="company-info-block">
      <div class="edit-btn"><a href='<?php echo BASE_URL;?>identitycodes/edit/id/<?php echo $this->dataArray[0]['id']; ?>'>Edit</a></div>
<table cellpadding="0" cellspacing="0" width="100%" border="0" >
<tr>
<td class="td-1" align="left" valign="top">
    <div class="site-info">
	      <label>Employee 
		      <b>:</b>
		  </label>
		  <span><?php echo $this->dataArray[0]['employee_code']; ?>
		  </span>
	</div>
	<?php if(sapp_Global::_isactivemodule(BGCHECKS)){ ?>
    <div class="site-info alter-div">
	      <label>Background Agency 
		      <b>:</b>
		  </label>
		  <span><?php echo $this->dataArray[0]['backgroundagency_code']; ?>
		</span>
    </div>
	<?php } ?>
    <div class="site-info ">
        <label>Users <b>:</b> </label>
        <span><div><?php echo $this->dataArray[0]['users_code']; ?></div></span>		
    </div>
	<?php if(sapp_Global::_isactivemodule(RESOURCEREQUISITION)) { ?>
    <div class="site-info alter-div">
        <label>Requisition <b>:</b> </label>
        <span><div><?php echo $this->dataArray[0]['requisition_code']; ?></div></span>		
    </div>
	<?php } ?>
	<div class="site-info">
	      <label>Description
		      <b>:</b>
		  </label>
		  <span><?php echo "Identitfication codes for different categories of people in an organization"; ?>
		  </span>
	</div>

</td>

</tr>
</table>
<?php } ?>
</div>
<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispsyspref').fadeOut('slow');
		},3000);

<?php } ?>

})
</script>