<?php 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller">
			
			<div class="new-form-ui clearb">
			  <label class="required">Date Format</label>
			<div class="division loca_state_div"><?php echo $this->form->dateformatid; ?></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label class="required">Time Format</label>
			<div class="division"><?php echo $this->form->timeformatid; ?></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label class="required">Default Currency</label>
			<div class="division"><?php echo $this->form->currencyid; ?></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label class="required">Default Password</label>
			<div class="division"><?php echo $this->form->passwordid; ?></div>
			<?php if(isset($this->msgarray['passwordid'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->passwordid->getId(); ?>"><?php echo $this->msgarray['passwordid'];?></span>
			<?php }?>
			</div>
					
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>

		
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>sitepreference';" type="button" >Cancel</button>
		</div>
</div>        