<?php $baseUrl = $this->serverUrl().$this->baseUrl();
?>
<div id="error_message" style="display:none;"></div>
<div class="poc-ui-data-control">

		<?php echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
		
		    <div class="new-form-ui">
			 <label id="injuredDate"><?php echo $this->form->educationlevel->getLabel(); ?></label>
				<div class="division loca_state_div"><?php echo $this->form->educationlevel; ?></div>
			</div>
			
		 	<div class="new-form-ui">
			  <label id="injuredDate">Institution Name</label>
				<div class="division loca_state_div"><?php echo $this->form->institution_name; ?></div>
			</div>
			
			<div class="new-form-ui ">
				<label>Course</label>
				<div class="division"><?php echo $this->form->course; ?></div>
			</div>
			
			<div class="new-form-ui ">
			    <label>From  </label>
				<div class="division"><?php echo $this->form->from_date; ?></div>
			</div>
															
			<div class="new-form-ui ">
			  <label>To  </label>
			  <div class="division"><?php echo $this->form->to_date; ?></div>
			</div>
				
			<div class="new-form-ui ">
			  <label>Percentage</label>
			  <div class="division"><?php echo $this->form->percentage; ?></div>
			</div>


        <div class="new-form-ui-submit" id="formSubmit">
        <input onclick="closeiframepopup('educationdetails','cancel');" type="button" value="close"  />
        </div>
</div>      
</form>

