<?php if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php 
}else{
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail cancel-set">
			<div class="new-form-ui clearb">
			  <label>Holiday</label>
			<div class="division"><?php echo $this->form->holidayname; ?></div>
			<?php if(isset($this->msgarray['holidayname'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->holidayname->getId(); ?>"><?php echo $this->msgarray['holidayname'];?></span>
			<?php }?>
			</div>
						
			<div class="new-form-ui clearb">
			  <label>Date </label>
			<div class="division"><?php echo $this->form->holidaydate; ?></div>
			<?php if(isset($this->msgarray['holidaydate'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->holidaydate->getId(); ?>"><?php echo $this->msgarray['holidaydate'];?></span>
			<?php }?>
			</div>
								
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
			
			<div class="new-form-ui-submit">
            <input onclick="closeiframepopup('<?php echo $this->controllername;?>','cancel');" type="button"  value="Close"  />
		</div>
       </div>
		
		
<?php } ?>		