<?php 
		if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>

<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
?>
        <div class="total-form-controller view-form-detail">
		<div class="new-form-ui clearb">
		  <label>Day</label>
	    <div class="division"><?php echo $this->form->day_name; ?></div>
		</div>
		
		<div class="new-form-ui clearb">
		  <label>Short Code</label>
	    <div class="division"><?php echo $this->form->dayshortcode; ?></div>
		</div>
		
		<div class="new-form-ui clearb">
		  <label>Long Code</label>
	    <div class="division"><?php echo $this->form->daylongcode; ?></div>
		</div>
		
		<div class="new-form-ui clearb textareaheight">
		  <label>Description</label>
		<div class="division"><?php echo $this->form->description; ?></div>
		</div>
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
				<button onclick="window.location.href='<?php echo BASE_URL; ?>weekdays';" type="button" >Cancel</button>
		</div>
</div>

<?php } ?>        