<?php if(sizeof($this->appData)>0){?>
<div class="cofig_title" style="margin-left: 0px; padding-top: 0px;">Appraisal Details</div>
	<table width="100%" cellspacing="0" cellpadding="0" border="0" class="requisition-table view-table-data" style="margin-bottom: 25px;">
		<tbody>
			
			<tr class="req-bg-form">
                <td width="20%"><span class="head_txt">Business Unit</span>   </td>
                <td width="30%"><?php echo $this->appData['unitname'];?></td>
                <td width="20%"><span class="head_txt">Department</span>  </td>
                <td width="30%"><?php echo isset($this->appData['deptname'])?$this->appData['deptname']:'--';?></td>
            </tr>
            <tr  class="req-no-form">
					<td><span class="head_txt">Appraisal Mode </span></td>
					<td><?php echo $this->appData['appraisal_mode'];?></td>
					<td><span class="head_txt">From Year </span></td>
					<td><?php echo $this->appData['from_year'];?></td>
			</tr> 
			<tr class="req-bg-form">
					<td><span class="head_txt">To Year </span></td>
					<td><?php echo $this->appData['to_year'];?></td>
					<td><span class="head_txt">Period </span></td>
					<td><?php 
					if($this->appData['appraisal_mode'] == 'Quarterly')
						echo "Q".$this->appData['appraisal_period'];
					else if($this->appData['appraisal_mode'] == 'Half-yearly')
						echo "H".$this->appData['appraisal_period'];
					else echo "Yearly";
					?></td>
			</tr>     
        </tbody>
	</table>
<?php }?> 
 