<?php 
//echo "coming here"; die;
//$data = $this->data;
$feedforwardInitForm = $this->feedforwardInitForm;
$appraisal_mode = $this->appraisal_mode;
   		 $appraisal_mode_period = $appraisal_mode['appraisal_mode'];
    	 $appraisal_form_year = $appraisal_mode['from_year']; 
    	 $appraisal_to_year = $appraisal_mode['to_year'];
    	 $appraisal_period = $appraisal_mode['appraisal_period'];
    	  
    $appraisal_mode = $appraisal_form_year.'_'.$appraisal_to_year.'_'.$appraisal_mode_period.'_'.$appraisal_period;
 	 $feedforwardInitForm->appraisal_mode->addMultiOption(1,utf8_encode($appraisal_mode));
 	// echo $feedforwardInitForm;
    //echo $appraisal_mode;
 	echo $feedforwardInitForm->appraisal_mode; 
 
?> 
 