<div class="tabscontainer">
	   
	  <div class="con_side">
	  		<div class="curvedContainer">
	  			<div  id="gridblock" class="activationsuccess">
	  			<div class="activecomplete"><?php echo $this->message;?></div>
	  			<div class="thankstxt">Click here to <a href="<?php echo $this->baseUrl(''); ?>" class="activationsuccesslink">Login</a></div>
	  			</div>
	  		</div>
	  </div>
</div>