<?php 
$options_data = "";
$options_data .= sapp_Global::selectOptionBuilder('', 'Select City');
if(!empty($this->citiesmodeldata))
{
	
	if($this->con == 'city')
	{
		foreach ($this->citiesmodeldata as $city) {
		$options_data .= sapp_Global::selectOptionBuilder($city['city_org_id'].'!@#'.$city['city'],utf8_encode($city['city']));
		}
		echo $options_data;
	}
	else{
		foreach ($this->citiesmodeldata as $city) {
		$options_data .= sapp_Global::selectOptionBuilder($city['id'].'!@#'.$city['city_name'],utf8_encode($city['city_name']));
		}
		if($this->con == 'otheroption')
		{
		  $options_data .= sapp_Global::selectOptionBuilder('other','Other');
		}
		echo $options_data;
	}
}else
{
  echo "nocities";
}
?> 