<?php 
$options_data = "";
$options_data .= sapp_Global::selectOptionBuilder('', 'Select Department');
if($this->con == 'leavemanagement')
{
  if(!empty($this->uniquedepartmentids))
  {
	   if($this->flag != 'true')
		{
		foreach ($this->uniquedepartmentids as $uniquedepartments) {
				$options_data .= sapp_Global::selectOptionBuilder($uniquedepartments['id'],utf8_encode($uniquedepartments['deptname']));
			}
			echo $options_data;
		}
		else
		{
		echo "nodepartments";
		}
  }
  else
  {
        if($this->flag != 'true')
		{
		foreach ($this->departmentlistArr as $departmentlist) {
				$options_data .= sapp_Global::selectOptionBuilder($departmentlist['id'],utf8_encode($departmentlist['deptname']));
			}
			echo $options_data;
		}
		else
		{
		echo "nodepartments";
		}
  }  

}
else if($this->con == 'appraisal_config')
{
	if(!empty($this->departmentlistArr))
  	{
	   if($this->flag != 'true')
		{
		foreach ($this->departmentlistArr as $departmentlist) {
				$options_data .= sapp_Global::selectOptionBuilder($departmentlist['id'],utf8_encode($departmentlist['deptname']));
			}
			echo $options_data;
		}
		
  	}
	else
	{
		echo "nodepartments";
	}
   
	
}
else
{
	if($this->flag != 'true')
	{
	foreach ($this->departmentlistArr as $departmentlist) {
			$options_data .= sapp_Global::selectOptionBuilder($departmentlist['id'],utf8_encode($departmentlist['deptname']));
		}
		echo $options_data;
	}

	else
	{
	echo "nodepartments";
	}
}
?>