<div id="dialog-confirm" style="display:none;">
    <div class="newframe-div">
        <div class="new-form-ui height32">
            <div class="division">
                <input type="text" maxlength="10" id="number_value" name="number_value">
            </div>
            <span class="errors" id="errors-contactnumber"></span>
        </div>
    </div>
</div>
<div id="empstatus-alert" style="display:none;">
    <div class="newframe-div">
        <div id="empstatusmessage"></div>
    </div>
</div>
<div id="empleaves-alert" style="display:none;">
    <div class="newframe-div">
        <div id="empleavesmessage"></div>
    </div>
</div>
<script type="text/javascript" language="javascript">
    //for menu div to be displayed
    $(document).ready(function() {
        var selected_obj = $('li[menu-url="/index.php/welcome"]');
        var parent_div = selected_obj.attr("parent-div");

        var controllerName = 'index';
        if (parent_div == '' || parent_div == null) {
            if (controllerName != 'error') {
                selected_obj = $("li[menu-url='http://hrms.cuelogic.co.in/index.php/index']");
            } else { // for not authorized pages.
            }
            parent_div = selected_obj.attr("parent-div");
        }
        if (parent_div == 'undefined') parent_div = '';
        /*Only for Service Desk */
        if (parent_div == '' || parent_div == null) {
            selected_obj = $("li[menu-url='http://hrms.cuelogic.co.in/index.php/welcome']");
            if (controllerName == 'servicerequests') {
                selected_obj = $("li[menu-url='http://hrms.cuelogic.co.in/index.php/servicerequests/index']");
            }
            parent_div = selected_obj.attr("parent-div");
        } //only for service desk

        selected_obj.addClass("active_menu_class");
        $('.' + parent_div).addClass("selected_menu_class");
        $('.' + parent_div).show();
        $('.acc_li_toggle').next().hide();
        parent_menu_selected(selected_obj);
        //removing of class for selected child menu
        $(".side-menu-selected").removeClass("side-menu-selected");
        //end of removing of class for selected child menu
        //to add selected class for selected child menu
        if (parent_div != "dummy")
            selected_obj.find("a").addClass("side-menu-selected");
        //end to add selected class for selected child menu
        //hide and show meu arrows by mouse events
        $("#menu-shadow").mouseenter(function(e) {

            var width = '';
            width = 1400;
            if ($('.menu-head').width() > width) { //hide scroll arrows if window width > 1310

                $('.simply-scroll-btn').hide();
            } else {
                $('.simply-scroll-btn').show();
            }
        });
        $("#menu-shadow").mouseleave(function(e) {
            $('.simply-scroll-btn').hide();
        });
        $("#mainmenushowhidebutton").click(function() {

            setdisplaymenu('display');
        });
    });

    function setdisplaymenu(flag) {
        if (flag == 'tour') {
            hideshow_mainmenu = 1;
        } else {
            if (hideshow_mainmenu == 1) hideshow_mainmenu = 0;
            else if (hideshow_mainmenu == 0) hideshow_mainmenu = 1;
        }
        $.ajax({
            type: "post",
            data: 'hideshow_mainmenu=' + hideshow_mainmenu,
            url: base_url + '/index/setsessionval',
            dataType: 'json',
            success: function(response) {
                if (response == 1) {
                    $("#menu-shadow").show(400);
                    $('#menu-hide-show').css('top', '-1px');
                    $('#mainmenushowhidebutton').children().addClass('show-menu');
                    $('#mainmenushowhidebutton').children().text('Click Here to Hide Menu');
                    $('#mainmenushowhidebutton').children().removeClass('hide-menu');
                } else if (response == 0) {
                    $("#menu-shadow").hide(400);
                    $('#menu-hide-show').css('top', '0');
                    $('#mainmenushowhidebutton').children().addClass('hide-menu');
                    $('#mainmenushowhidebutton').children().text('Click Here to Show Menu');
                    $('#mainmenushowhidebutton').children().removeClass('show-menu');
                }
            }
        });
    }

    function togglesubmenus(id) {
        $('#acc_li_toggle_' + id).next().toggle();
        if ($('#acc_li_toggle_' + id).next().is(":visible") == true) {
            $('#acc_li_toggle_' + id).removeClass('acc_li_toggle');
            $('#acc_li_toggle_' + id).addClass('acc_li_toggle_down');
        } else {
            $('#acc_li_toggle_' + id).removeClass('acc_li_toggle_down');
            $('#acc_li_toggle_' + id).addClass('acc_li_toggle');
        }
    }

    function parent_menu_selected(selected_obj) {
        //start for removing selected class in parent menu
        var already_selected_obj = $('.super_selected').parent().parent();
        var already_selected_id = already_selected_obj.prop('id');
        var already_selected_class = already_selected_obj.attr("selected-class");
        $('#' + already_selected_id + " span").removeClass(already_selected_class);
        $('#' + already_selected_id + " span").removeClass("super_selected");
        $('#' + already_selected_id).removeClass("link-selected");
        var dashboard_menu = 'main_parent_173';
        if (already_selected_id == undefined) //when dashboard selectes undefined will come
        {
            $('#' + dashboard_menu).removeClass("link-selected");
        }
        //end for removing selected class in parent menu
        //to add selected class for parent menu
        var super_parent = selected_obj.attr("super-parent");
        var super_selected_class = $('#' + super_parent).attr("selected-class");
        $('#' + super_parent + " span").addClass(super_selected_class);
        $('#' + super_parent + " span").addClass("super_selected");
        $('#' + super_parent).addClass("link-selected");
        //end to add selected class for parent menu

        var primary_parent = selected_obj.attr("primary_parent");
        if (primary_parent != '' && typeof(primary_parent) != 'undefined') {
            togglesubmenus(primary_parent);
        }

    }
</script>
<script language='javascript'>
    function hide() {
        alert('hide')
    }

    function show() {
        alert('show');
    }
</script>
<!--assessment goal starts here-->
<div class="main-wrapper-okrs">
    <!--Header section of the page starts here-->
    <div class="okrs-header">
        <h2 class="pull-left">Assessment Details</h2>
        <div class="pull-right">
            <div class="active-btn">Save</div>
        </div>
    </div>
    <!--Header section of the page ends here-->
    <div class="assessment-details-left">
        <div class="goal-details-content-bg">
            <div class="goal-details-headers">
                <div class="goal-title">Name of the Goal</div>
                <div class="goal-followers">10 followers</div>
                <div class="goal-icon"><img src="<?php echo MEDIA_PATH;?>images/okr/goal_icon.png"></div>
            </div>
            <div class="goal-details-inside-bg-1">
                <div class="goal-description">description of the goal</div>
                <div class="goal-assessment">Assessment: 2</div>
            </div>
            <div class="goal-linked">Linked to: name of the goal to which this goal is linked, clicking on this will take you that goal</div>
            <div class="goal-details-inside-bg-2">
                <div class="goal-details-text-left">Owner: Ninad Shah</div>
                <div class="goal-details-text-right">Last Updated: 24hrs</div>
            </div>
            <div class="goal-details-inside-bg-2">
                <div class="goal-details-text-left">Progress: 10%</div>
                <div class="goal-details-text-right">Due Date: 10/06/16</div>
            </div>
            <div class="goal-details-inside-bg-2">
                <div class="goal-details-text-left">
                    Keywords: Process, Okrs, HR</div>
                <div class="goal-details-text-right">Quarter:Q3</div>
            </div>
        </div>


        <div class="milestone-details-content-bg">
            <div class="goal-details-inside-bg-1">
                <div class="milestone-details">code coverage Second line if coverage is long</div>
                <div class="milestone-edit-btn"><div class="gray-btn">edit</div></div>
                <div class="milestone-icon"><img src="<?php echo MEDIA_PATH;?>images/okr/collapse-menu.png"></div>
            </div>
            <div class="goal-details-inside-bg-1">
                <div class="milestone-assesments">Assessment: 2</div>
            </div>
            <div class="goal-details-inside-bg-1">
                <div class="milestone-percentage">10%</div>
                <div class="milestone-percentage-target">Target: 99%</div>
            </div>
            <div class="goal-details-inside-bg-1">
                <div class="milestone-comments">Comments</div>
                <div class="milestone-comments-icon"><img src="<?php echo MEDIA_PATH;?>images/okr/comments-icon.png"></div>
                <div class="milestone-updated">Last Updated:24 hrs</div>
                <div class="milestone-btns">
                    <div class="gray-btn">cancel</div>
                    <div class="active-btn">save</div>
                </div>
            </div>
        </div>
    </div>


    <div class="assessment-details-right">
        <div class="pre-assessments-bg">
            <!--previous assessments-->
            <div class="updates-details">
                <div class="update-top-section">
                    <div class="updates-profile">
                        <img src="<?php echo MEDIA_PATH;?>images/okr/employee-deafult-pic1.png" alt="">
                        <p class="employee-name">Ninad Shah</p>
                    </div>
                    <div class="assessment-content">
                        <div class="assessment-score">Score 4/10</div>
                        <div class="assessment-time">30 mins back</div>
                    </div>
                </div>
                <div class="assessment-content comment-section">
                    <div class="assessment-comment-display">
                        The first 50 or 100 words of the comment should come here. The comment box should be clickable if their is more comment than the box or area can fill
                    </div>
                </div>
            </div>
            <div class="updates-details">
                <div class="update-top-section">
                    <div class="updates-profile">
                        <img src="<?php echo MEDIA_PATH;?>images/okr/employee-deafult-pic1.png" alt="">
                        <p class="employee-name">Ninad Shah</p>
                    </div>
                    <div class="assessment-content">
                        <div class="assessment-score">Score 4/10</div>
                        <div class="assessment-time">30 mins back</div>
                    </div>
                </div>
                <div class="assessment-content comment-section">
                    <div class="assessment-comment-display">
                        The first 50 or 100 words of the comment should come here. The comment box should be clickable if their is more comment than the box or area can fill
                    </div>
                </div>
            </div>
            <div class="updates-details">
                <div class="update-top-section">
                    <div class="updates-profile">
                        <img src="<?php echo MEDIA_PATH;?>images/okr/employee-deafult-pic1.png" alt="">
                        <p class="employee-name">Ninad Shah</p>
                    </div>
                    <div class="assessment-content">
                        <div class="assessment-score">Score 4/10</div>
                        <div class="assessment-time">30 mins back</div>
                    </div>
                </div>
                <div class="assessment-content comment-section">
                    <div class="assessment-comment-display">
                        The first 50 or 100 words of the comment should come here. The comment box should be clickable if their is more comment than the box or area can fill
                    </div>
                </div>
            </div>
            <div class="updates-details">
                <div class="update-top-section">
                    <div class="updates-profile">
                        <img src="<?php echo MEDIA_PATH;?>images/okr/employee-deafult-pic1.png" alt="">
                        <p class="employee-name">Ninad Shah</p>
                    </div>
                    <div class="assessment-content">
                        <div class="assessment-score">Score 4/10</div>
                        <div class="assessment-time">30 mins back</div>
                    </div>
                </div>
                <div class="assessment-content comment-section">
                    <div class="assessment-comment-display">
                        The first 50 or 100 words of the comment should come here. The comment box should be clickable if their is more comment than the box or area can fill
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--assessment goal ends here-->
