
<?php if (count($this->messages)) {?>
	<div id="dispmsgmanager">
    <div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
		<?php foreach ($this->messages as $message){?>
		 <?php echo $this->escape($message); ?>
		<?php } ?>
      </div>  
	</div>	
	
<?php } ?>
<?php if($this->call != 'ajaxcall' && count($this->nextLevelManagers) > 0) { ?>
<div style="margin-bottom: 10px; float:right;" id="nextManagers">
	<select id="nextManagersSelect">
		<option value="">My Team</option>
		<?php foreach($this->nextLevelManagers as $managers) : ?>
			<option value="<?php echo $managers['user_id']; ?>"><?php echo $managers['userfullname']; ?></option>
		<?php endforeach;?>
	</select>
</div>
<?php } ?>
<span id="error_message"></span>
<?php 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
?>

<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgmanager').fadeOut('slow');
		},3000);

<?php } ?>
<?php if($this->call != 'ajaxcall') { ?>
	if($("#nextManagers").length > 0) {
		$('#nextManagersSelect').on('change', function(e) {
			console.log("Value changed");
			var url = "<?php echo BASE_URL; ?>manageremployeevacations/index/format/html";
			console.log(url);
			$.post(url,
					{
						per_page:20,
						page:1,
						call:'ajaxcall',
						objname:'manageremployeevacations',
						dashboardcall:'No',
						sort:'DESC',
						by:'createddate',
						manager_Id:$('#nextManagersSelect').val()
					}, 
					function(data){
						//console.log(data);
						$('#grid_manageremployeevacations').html(data);
					}
			);
		});
	}
<?php } ?>	

})
</script>
