<?php
if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php 
}else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
		 
			<div class="new-form-ui">
			  <label>Employee Name</label>
			<div class="division"><?php echo $this->form->employeename; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Leave Type</label>
			<div class="division"><?php echo $this->form->leavetypeid; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Leave</label>
			<div class="division"><?php echo $this->form->leaveday; ?></div>
			</div>
			
			<div class="new-form-ui textareaheight">
			  <label>Reason</label>
			<div class="division"><?php echo $this->form->reason; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>From Date</label>
			<div class="division"><?php echo $this->form->from_date; ?></div>
			</div>
			
			<div class="new-form-ui" id="todate_employee">
			  <label>To Date</label>
			<div class="division"><?php echo $this->form->to_date; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Number of Days</label>
			<div class="division"><?php echo $this->form->appliedleavesdaycount; ?></div>
			</div>
			
			
			<div class="new-form-ui">
			  <label>Applied On</label>
			<div class="division"><?php echo $this->form->createddate; ?></div>
			</div>
			
			<!--<div class="new-form-ui">
			  <label>Status</label>
				<div class="division"><?php //echo $this->form->leavestatus; ?></div>
			</div>-->
			
			<div class="new-form-ui-submit">
			 	<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>manageremployeevacations';"  type="button"  value="Back"  />
		    </div>
        </div>
<?php } ?>		

<script type='text/javascript'>
$(document).ready(function(){
   <?php if($this->data['leaveday'] == 2){?>
           $("#todate_employee").hide();
   <?php }?>
});
</script>