<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}	else	{

	 if(!empty($this->employeedata))
	 {
			echo $this->employeedetails($this->employeedata,'mydetails',$this->id); 
	 } 
?>
<div class="right-block-data">
		<?php echo $this->form->id; 
			echo $this->form->user_id;
			?>
			<div class="total-form-controller view-form-detail">
				<div class="new-form-ui">
				  <label>Personal Email</label>
				<div class="division"><?php echo $this->form->personalemail; ?></div>
				</div>
				
				<div class="separetor-heading">Permanent Address</div>			
	
    			<div class="new-form-ui">
				  <label>Street Address</label>
				<div class="division"><?php echo $this->form->perm_streetaddress; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label>Country</label>
				<div class="division"><?php echo $this->form->perm_country; ?></div>
				</div>
												
				<div class="new-form-ui">
				  <label>State</label>
				<div class="division"><?php echo $this->form->perm_state; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label>City</label>
				<div class="division"><?php echo $this->form->perm_city; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label>Pincode</label>
				<div class="division"><?php echo $this->form->perm_pincode; ?></div>
				</div>

				<div class="separetor-heading">Current Address</div>				
                
				<div class="new-form-ui">
				<label >Street Address</label>
				<div class="division"><?php echo $this->form->current_streetaddress; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label >Country</label>
				<div class="division"><?php echo $this->form->current_country; ?></div>
				</div>
												
				<div class="new-form-ui">
				  <label >State</label>
				<div class="division"><?php echo $this->form->current_state; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label >City</label>
				<div class="division"><?php echo $this->form->current_city; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label >Pincode</label>
				<div class="division"><?php echo $this->form->current_pincode; ?></div>
				</div>
				
				<div class="separetor-heading">Emergency Details</div>
				<div >
					<div class="new-form-ui">
					  <label >Name 1</label>
					<div class="division"><?php echo $this->form->emergency_name_1; ?></div>
					</div>
					
					
					<div class="new-form-ui">
					  <label >Number 1</label>
					<div class="division"><?php echo $this->form->emergency_number_1; ?></div>
					</div>

					<div class="new-form-ui">
					  <label >Relation</label>
					<div class="division"><?php echo $this->form->relation_emergency_1; ?></div>
					</div>
					
				</div>
				<div class="separetor-heading">
					<div class="new-form-ui">
					  <label >Name 2</label>
					<div class="division"><?php echo $this->form->emergency_name_2; ?></div>
					</div>
					
					<div class="new-form-ui">
					  <label >Number 2</label>
					<div class="division"><?php echo $this->form->emergency_number_2; ?></div>
					</div>
					
					<div class="new-form-ui">
					  <label >Relation</label>
					<div class="division"><?php echo $this->form->relation_emergency_2; ?></div>
					</div>
					
				</div>
			  <div class="separetor-heading">Work Address</div>
				<div class="work-address">
					<div class="division">
							<?php
							if(!empty($this->dataArray))
							{
								$address1 = explode(',',$this->dataArray['address1']);
								for($i=0;$i<sizeof($address1);$i++)
								{
									echo $address1[$i].',<br>';
								}
                                if($this->dataArray['city'] !='')								
								  echo $this->dataArray['city'].', ';
								if($this->dataArray['state'] !='')  
								  echo $this->dataArray['state'].', ';
								if($this->dataArray['country'])  
								  echo $this->dataArray['country'].'.';
							}	
							?>
					</div>
				</div>
			</div>
          <div class="new-form-ui-submit">
			<?php	/*	If the login employee has edit privilege then show edit ...		*/
			if($this->editPrivilege == 'Yes')	{	?>
        	<input type="button" onclick="redirecttoEditscreen('<?php echo $this->controllername;?>','<?php echo $this->actionname;?>');" value="Edit" />    
		<?php	}	?>
		</div>
</div>
</div>

<script type='text/javascript'>
$(document).ready(function(){
    $("#empcommunicationdetails").addClass('active');
   $("#empcommunicationdetails").removeAttr("onclick");

})
</script>

<?php }?>