<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}	else	{
$baseUrl = $this->serverUrl().$this->baseUrl();

?><div id="error_message" style="display:none;"></div>
<?php if($this->call != 'ajaxcall')	{ ?>
<?php if(!empty($this->empdata))
 {
    	echo $this->employeedetails($this->empdata[0],'mydetails',$this->id); 
 } 		?>

<div class="right-block-data"> 
<?php	}
		if($this->call == 'ajaxcall')
		{
			$div = ''; $endDiv = ''; 
		}
		else 
		{ 
			$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
		}
		echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->employeegrid($this->dataArray[0]).$endDiv;

		if($this->call != 'ajaxcall')	{?>
</div>	
</div>

<div id="dependencydetailsContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
		<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right"
			border="0" hspace="3" vspace="5" class="closeAttachPopup"
			style="margin: -24px 8px 0 0;"> </a>
	</div>
	<iframe id="dependencydetailsCont" class="business_units_iframe" frameborder="0"></iframe>

</div>
<?php	}	?>
<script type='text/javascript'>
$(document).ready(function(){
	$("#dependency_details").addClass('active');
	$("#dependency_details").removeAttr("onclick");
});
</script>
<?php	}	?>