<?php	
 if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php 
}	else	{
$baseUrl = $this->serverUrl().$this->baseUrl();
?>
<?php if (count($this->messages)) {?>
	<div id="dispmsgempleaves" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php } ?>

<?php if($this->call != 'ajaxcall'){ ?>
<?php if(!empty($this->empdata))
 {
       	echo $this->employeedetails($this->empdata[0],'mydetails',$this->id); 
 } 
?>
<div class="right-block-data"> 
<div id="error_message" style="display:none;"></div>
	
<?php } 	
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control mrgetop20">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->employeegrid($this->dataArray[0]).$endDiv;
?>
<?php	if($this->call != 'ajaxcall'){	?>
</div>	
</div>
<?php	}	?>
<div id="empleavesContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
		<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right"
			border="0" hspace="3" vspace="5" class="closeAttachPopup"
			style="margin: -24px 8px 0 0;"> </a>
	</div>

		<iframe id="empleavesCont" class="business_units_iframe" frameborder="0"></iframe>

</div>
<script type='text/javascript'>
$(document).ready(function(){

	$('.grid tbody tr').each(function(i,v){
		var lb = $(v).find('td:eq(3) span').html();
		var pb = $(v).find('td:eq(4) span').html();
		if(lb > 0)
			$(v).find('td:eq(3) span').html(lb-pb);
	});
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgempleaves').fadeOut('slow');
		},3000);

<?php } ?>

    $("#emp_leaves").addClass('active');
	$("#emp_leaves").removeAttr("onclick");


})
</script>
<?php } ?>