<?php 
		if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>

<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        
        <div class="total-form-controller view-form-detail">
		    <div class="new-form-ui clearb">
			  <label>Country</label>
			<div class="division"><?php echo $this->form->countryid; ?></div>
		    </div>
			<div class="new-form-ui clearb">
			  <label>State</label>
			 <div class="division"><?php echo $this->form->state; ?></div>
			</div>
		<div class="new-form-ui-submit">
            <input onclick="window.location.href='<?php echo BASE_URL; ?>states';" type="button" value="Back" />
			</div>
</div>
		
<script type='text/javascript'>
 <?php if($this->stateValue!='') { ?>
	
			var stateval = '<?php echo $this->stateValue; ?>';
			var stateData = document.getElementById('state');
			for(var i = 0 ; i <= stateData.length ; i++)
			{
				if(stateData.options[i] !== undefined)
				{
					if (stateData.options[i].value == stateval) 
					{
						stateData.options[i].selected = true;
						break;
					}
				}
			}
			
	<?php } ?>	
</script>	

<?php } ?>	