<?php 
//echo $this->message;
?>
<div class="total-form-controller">
<div class="separetor-heading">candidate Details</div>
	<div class="new-form-ui">
            <label class="required">Requisition Code</label>
            <div class="division"><select></select></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Candidate Name</label>
             <div class="division"><input type="text" /></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Email Id</label>
	        <div class="division"><input type="text" /></div>
	</div>
   	<div class="new-form-ui">
            <label class="required">Resume</label>
            <div class="division"><input type="file" /></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Qualification</label>
	        <div class="division"><input type="text" /></div>
	</div>
     <div class="new-form-ui">
            <label class="required">Work Experience</label>
	        <div class="division"><input type="text" /></div>
	</div>
    <div class="new-form-ui">
            <label class="required">Email Id</label>
	        <div class="division"><input type="text" /></div>
	</div>
	<div class="new-form-ui textareaheight">
            <label class="required">Skill Set</label>
            <div class="division">
            <span class="textarea-data-show">Contrary to popular belief
            Lorem Ipsum is
            not simply random text. 
            It has roots in a piece 
            of classical Latin literature</span></div>
    </div>
	<div class="new-form-ui textareaheight">
            <label class="required">Summary</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</span></div>
    </div>
	<div class="new-form-ui textareaheight">
            <label class="required">Education Summary</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature , It has roots in a piece of classical Latin literature, It has roots in a piece of classical Latin literature, It has roots in a piece of classical Latin literature</span></div>
    </div>


<div class="new-form-ui-submit">
		<input type="submit" value="save" />
		<button type="button" id="Cancel" name="Cancel">Cancel</button>
</div>  

</div>