<?php 
$options_data = "";	

	if($this->flag != 'true')
	{
            $options_data .= sapp_Global::selectOptionBuilder('', 'Select A Reporting Manager');
		foreach ($this->RMdata as $opt) {
			$options_data .= sapp_Global::selectOptionBuilder($opt['id'],ucwords(utf8_encode($opt['name'])),$opt['profileimg'] );
		}
		echo $options_data;
	}
	else
	{
	    echo "nomanagers";
	}

?> 
 