<?php 
$auth = Zend_Auth::getInstance();

if (count($this->messages)) 
{?>
	<div id="dispscreeningtype" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php } ?>
<div id="error_message"></div>
<?php 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->requisitiongrid($this->dataArray).$endDiv;
?>
<script type="text/javascript" language="javascript">

$(document).ready(function(){
   
        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');?>
    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                    successmessage('<?php echo trim($msg); ?>');                    
            <?php endforeach; ?>
    <?php endif; ?>
});

</script>