<?php if(empty($this->empdata)){?>
    <div class="ml-alert-1-info">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
					No data found.
				<?php }else{?>
						Employee inactivated.
				<?php }?>
	</div>
<?php
} else {
?>
<?php	
$baseUrl = $this->serverUrl().$this->baseUrl();

if(!empty($this->employeedata))
 {
 	echo $this->employeedetails($this->employeedata,'view',$this->id); 
 } 
?>

<div class="right-block-data right-over-border"> 
	<div id="error_message" style="display:none;"></div>
		<div class="ml-alert-1-info m1-info-set">
			<div class="style-1-icon info"></div>Feature will be available soon.
		</div>	
</div>	
</div>
<?php 
}
?>
<script type='text/javascript'>
$(document).ready(function(){
    $("#emp_payslips").addClass('active');
    $("#emp_payslips").removeAttr("onclick");

});
</script>
