<?php 
$options_data = "";
   $options_data .= sapp_Global::selectOptionBuilder('', 'Select Approver '.$this->approvercount);
if(!empty($this->employeedata))
{
		foreach ($this->employeedata as $employee) {
			$options_data .= sapp_Global::selectOptionBuilder($employee['user_id'],utf8_encode($employee['userfullname']));
		}
		echo $options_data;
	
}else
{
  echo "noemployees";
}
?> 
 