<?php sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        <div class="total-form-controller">
		    <div class="new-form-ui clearb">
			  <label class="required">Group Name</label>
			<div class="division"><?php echo $this->form->groupname; ?></div>
			<?php if(isset($this->msgarray['groupname'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->groupname->getId(); ?>"><?php echo $this->msgarray['groupname'];?></span>
			<?php }?>
			</div>
								
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
	
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>holidaygroups';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
</div>
</form>
