<?php if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
			<div class="new-form-ui clearb">
			  <label>Group Name</label>
			<div class="division"><?php echo $this->form->groupname; ?></div>
			</div>
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<?php if(($this->editpermission == 'Yes')) { ?>
					 <input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
					<button onclick="window.location.href='<?php echo BASE_URL; ?>holidaygroups';" type="button" >Cancel</button>
				   <?php }
				   else{
				    ?>
					<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>holidaygroups';" type="button"  value="Back"  />
    	           <?php } ?>
		</div>
</div>		
<span id="error_message"></span>
<?php 
if($this->groupdataCount > 0) { 
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;

?>

<div id="<?php echo $this->controllergrid;?>Container"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
		<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right"
			border="0" hspace="3" vspace="5" class="closeAttachPopup"
			style="margin: -24px 8px 0 0;"> </a>
	</div>

		<iframe id="<?php echo $this->controllergrid;?>Cont" class="holiday_groups_iframe" frameborder="0"></iframe>

</div>	

<?php }}?>		