<?php if (count($this->messages)) {?>
<div id="dispmsgmygroup">
  <div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
		<?php foreach ($this->messages as $message){?>
		 <?php echo $this->escape($message); ?>
		<?php } ?>
</div>
	</div>	
	
<?php } ?>
<?php if($this->errormessage !=''){?>
       <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>Holiday group is not configured yet. Please contact your HR.
		</div>

<?php }else {?>
<span id="error_message"></span>
<?php 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
}?>

<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgmygroup').fadeOut('slow');
		},3000);

<?php } ?>

});
</script>

