<?php if($this->ermsg == 'nodata') { ?>
<div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php } else { ?>
<?php 
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail cancel-set">
			<div class="new-form-ui clearb">
			  <label>Holiday</label>
			<div class="division"><?php echo $this->form->holidayname; ?></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label>Holiday Group</label>
			<div class="division"><?php echo $this->form->groupid; ?></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label>Date</label>
			<div class="division"><?php echo $this->form->holidaydate; ?></div>
			</div>
								
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
        <input onclick="window.location.href='<?php echo BASE_URL; ?>myholidaycalendar';" type="submit"  value="Back" />
		</div>
</div>        
<?php } ?>