<?php 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
			<div class="new-form-ui">
			  <label>Leave Type</label>
			<div class="division"><?php echo $this->form->leavetype; ?></div>
			</div>	
			<div class="new-form-ui">
			  <label>Number of Days</label>
			<div class="division"><?php echo $this->form->numberofdays; ?></div>
			</div>
			<div class="new-form-ui">
			  <label >Leave Short Code</label>
			<div class="division"><?php echo $this->form->leavecode; ?></div>
			</div>
			<div class="new-form-ui">
			  <label >Is Pre Allocated</label>
			<div class="division"><?php echo $this->form->leavepreallocated; ?></div>
			</div>
			<div class="new-form-ui">
			  <label >Is Deductible</label>
			<div class="division"><?php echo $this->form->leavepredeductable; ?></div>
			</div>
			<div class="new-form-ui textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>employeeleavetypes';" type="button" >Cancel</button>
		</div>
</div>      
<?php	}	?>  