<div id="error_message" style="display: none;"></div>
<?php
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = '';
} else {
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->logsgrid($this->dataArray[0]).$endDiv;
?>




