<div class="award-sidebar">
    <header>
        <img src="<?php echo MEDIA_PATH;?>images/hall-of-fame-img.png">
    </header>
    <ul>
        <li><span class="fa fa-trophy"></span><a href="javascript:void(0);">Award Category 1</a></li>
        <li><span class="fa fa-trophy"></span><a href="javascript:void(0);">Award Category 2</a></li>
        <li><span class="fa fa-trophy"></span><a href="javascript:void(0);">Award Category 3</a></li>
    </ul>
</div>