<?php if($this->ermsg == 'nodata') {?>
<div class="ml-alert-1-info">
<div class="style-1-icon info"></div>No data found.
</div>
<?php } else { ?>
<?php 

$messages = $this->messages;
$edit_flag = $this->edit_flag;
$data = $this->data;
$form = $this->form;
$round_count = $this->round_count;
?>
<?php if($this->popup == 'close') { ?>

<?php } else { ?>

    <?php echo $form->id;
          
    ?>
<div class="total-form-controller view-form-detail">
   
<input type="hidden" value="<?php echo $this->deptid;?>" id="deptidform" name="deptidform" />
    <div class="new-form-ui">
        <label >Interviewer</label>
        <div class="division"><?php echo $form->interviewer_id;?></div>
        <span id="errors-interviewer_id" class="errors"><?php echo (isset($messages['interviewer_id'])?$messages['interviewer_id']:"");?></span>
    </div>
    <div class="new-form-ui">
        <label >Location</label>
        <div class="division"><?php echo $form->int_location;?></div>
        <span id="errors-int_location" class="errors"><?php echo (isset($messages['int_location'])?$messages['int_location']:"");?></span>
    </div>
	<div class="new-form-ui">
        <label>Country</label>
	<div class="division">
            <select disabled>
                <option><?php  echo $this->country_name;?></option>
            </select>
        </div>		
    </div>
	
    <div class="new-form-ui container_left">
        <label>State</label>
	<div class="division">
            <select disabled>
                <option><?php echo $this->state_name;?></option>
            </select>            
        </div>		
    </div>
	
    <div class="new-form-ui container_left">
        <label>City</label>
	<div class="division">
            <select disabled>
                <option><?php echo $this->city_name;?></option>
            </select>            
        </div>		
    </div>
    <div class="new-form-ui">
        <label >Interview Type</label>
        <div class="division"><?php echo $form->interview_mode;?></div>
        <span id="errors-interview_mode" class="errors"><?php echo (isset($messages['interview_mode'])?$messages['interview_mode']:"");?></span>
    </div>
<div class="new-form-ui">
        <label >Interview Date</label>
        <div class="division"><input type="text" readonly="readonly" onfocus = "this.blur()" value="<?php echo $form->interview_date->getValue();?>" /></div>
        <span id="errors-interview_date" class="errors"><?php echo (isset($messages['interview_date'])?$messages['interview_date']:"");?></span>
    </div>
    <div class="new-form-ui">
        <label >Interview Time</label>
        <div class="division"><?php echo $form->interview_time;?></div>
        <span id="errors-interview_time" class="errors"><?php echo (isset($messages['interview_time'])?$messages['interview_time']:"");?></span>
    </div>
	<div class="new-form-ui">
		<label >Interview Name</label>
		  <div class="division"><?php echo $form->interview_round;?></div>
		  <span id="errors-interview_time" class="errors"><?php echo (isset($messages['interview_round'])?$messages['interview_round']:"");?></span>
    </div>
    
	
	 <div class="new-form-ui textareaheight">
        <label >Interviewer Feedback</label>
        <div class="division"><?php echo $form->interview_feedback;?></div>
        <span id="errors-interview_date" class="errors"><?php echo (isset($messages['interview_feedback'])?$messages['interview_feedback']:"");?></span>
    </div>
	
	 <div class="new-form-ui textareaheight">
        <label >Interviewer Comments</label>
        <div class="division"><?php echo $form->interview_comments;?></div>
        <span id="errors-interview_date" class="errors"><?php echo (isset($messages['interview_comments'])?$messages['interview_comments']:"");?></span>
    </div>
	
	 <div class="new-form-ui">
        <label >Round Status</label>
        <div class="division"><?php echo $form->round_status;?></div>
        <span id="errors-interview_date" class="errors"><?php echo (isset($messages['round_status'])?$messages['round_status']:"");?></span>
    </div> 
<div class="new-form-ui-submit">
   <?php 
   if($edit_flag == 'yes')
   {
   ?>
       <input type="button" value="Edit" onclick="window.location.href='<?php echo BASE_URL.'interviewrounds/editpopup/unitId/'.$this->intId.'/id/'.$this->roundId;?>'" />        
<?php 
   }
   ?>
<input type="button" onclick="closeiframepopup('interviewrounds','cancel');" id="Cancel" name="Cancel" value="Close" />

</div>
</div>

<?php }
} ?>
<script language='javascript'>

<?php if($this->popup != '') { ?>
        setTimeout(function(){
		    closeiframepopup('interviewrounds','refreshgrid'); 
		},2000);
<?php } ?>
</script>
