<?php	
$baseUrl = $this->serverUrl().$this->baseUrl();

if(!empty($this->employeedata))
 {
 	echo $this->employeedetails($this->employeedata,'view',$this->id); 
 } 
?>

<div class="right-block-data"> 
	<div id="error_message" style="display:none;"></div>
		<div class="ml-alert-1-info m1-info-set">
			<div class="style-1-icon info"></div>Feature will be available soon.
		</div>	
</div>	
</div>
<script type='text/javascript'>
$(document).ready(function(){
    $("#emp_reqdetails").addClass('active');
    $("#emp_reqdetails").removeAttr("onclick");

});
</script>
