<div class="configure-site-div">

<div class="confi-menu">
	<ul>
    	<li><a href="<?php echo BASE_URL; ?>configuresite/index"><div class="confige-sprite site-config-icon"></div><p>Site Configuration</p></a></li>
        <li><a href="#" class="selected"><div class="confige-sprite manage-icon-selected"></div><p>Manage Menu</p></a></li>
        <li><a href="<?php echo BASE_URL; ?>configuresite/sitepreferences"><div class="confige-sprite prefi-icon"></div><p>Site preferences</p></a></li>
    </ul>

</div>

<div class="confi-block-2">
	<div class="confi-total-detail">
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data-now"></a><a href="#" class="confige-sprite deactive-data"></a></span>
       </div>
       <div class="managemenu-list">
       	<p>Date Format</p><span><a href="#" class="confige-sprite active-data"></a><a href="#" class="confige-sprite deactive-data-now"></a></span>
       </div>
     </div>  
</div>

</div>



