<?php if($this->ermsg == 'nodata') {?>
<div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php }else { ?>
<?php 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
			<div class="new-form-ui clearb">
			  <label>Screening Type</label>
			<div class="division"><?php echo $this->form->type; ?></div>
			</div>
			
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<?php if($this->permission == 'Yes'){?>
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<?php } ?>			
			<button onclick="window.location.href='<?php echo BASE_URL; ?>bgscreeningtype';" type="button" >Cancel</button>
		</div>
</div> 
<?php } ?>       