<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
        <div class="total-form-controller view-form-detail">
		 	<div class="new-form-ui ">
			  <label id="injuredDate">Skill</label>
				<div class="division loca_state_div"><?php echo $this->form->skillname; ?></div>
			</div>
			
			<div class="new-form-ui ">
				<label>Years of Experience</label>
				<div class="division"><?php echo $this->form->yearsofexp; ?></div>
			</div>
			
			<div class="new-form-ui ">
			    <label>Competency Level</label>
				<div class="division"><?php echo $this->form->competencylevelid; ?></div>
			</div>

			<div class="new-form-ui ">
			<label >Skill Last Used Year</label>
			<div class="division"><?php echo $this->form->year_skill_last_used; ?></div>
			</div>

        <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('empskills','cancel');" type="button" value="Close"  />
        </div>
 

</div>       
        