<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
        <div class="total-form-controller view-form-detail">
		 	<div class="new-form-ui clearb">
			  <label>Holiday</label>
			<div class="division"><?php echo $this->form->holidayname; ?></div>
			<?php if(isset($this->msgarray['holidayname'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->holidayname->getId(); ?>"><?php echo $this->msgarray['holidayname'];?></span>
			<?php }?>
			</div>
						
			<div class="new-form-ui clearb">
			  <label>Date </label>
			<div class="division"><?php echo $this->form->holidaydate; ?></div>
			<?php if(isset($this->msgarray['holidaydate'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->holidaydate->getId(); ?>"><?php echo $this->msgarray['holidaydate'];?></span>
			<?php }?>
			</div>
								
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>


        <div class="new-form-ui-submit" id="formSubmit">
        <input onclick="closeiframepopup('empholidays','cancel');" type="button" value="Close"  />
        </div>
</div>