<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>		
    
	<span style='color:#3b3b3b;'>Hello <?php echo $this->emp_name;?>,</span><br />
	
	<div style='padding:20px 0 10px 0;'>		
		Your time sheet has been blocked for the period <?php echo $this->period;?>. Please approach your manager for enabling your time sheet. 
	</div>
			
	<div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url;?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the time sheet details.</div>

</div> 