<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
    
	<span style='color:#3b3b3b;'>Dear <?php echo ucfirst($this->emp_name);?>,</span><br />
	
	<div style='padding:20px 0 0 0;'>		
		Your time sheet submission is pending for the following days.<br/>
	</div>
			
	<div style='padding:10px 0 0 0;'>
		<ol>
		<?php 
		foreach($this->days as $date)
		{
		?>
			<li> <?php echo date('m-d-Y',strtotime($date));?></li>
		<?php 
		}
		?>
		</ol>
	</div>	
	
	<div style="padding:20px 0 10px 0;">Please <a href="<?php echo $this->base_url;?>" target="_blank" style="color:#b3512f;">click here</a> to login and check the time sheet details.</div>

</div>      
	  

