<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
			<div class="new-form-ui">
			  <label>Job Title Code</label>
			<div class="division"><?php echo $this->form->jobtitlecode; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Job Title</label>
			<div class="division"><?php echo $this->form->jobtitlename; ?></div>
			</div>
					
			<div class="new-form-ui textareaheight">
			  <label>Job Description</label>
			<div class="division"><?php echo $this->form->jobdescription; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Min Experience Required</label>
			<div class="division"><?php echo $this->form->minexperiencerequired; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Job Pay Grade Code</label>
			<div class="division"><?php echo $this->form->jobpaygradecode; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Job Pay Frequency</label>
			<div class="division"><?php echo $this->form->jobpayfrequency; ?></div>
			</div>
			
			<div class="new-form-ui textareaheight">
			  <label>Comments</label>
			<div class="division"><?php echo $this->form->comments; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>jobtitles';" type="button" >Cancel</button>
		</div>
</div>     
<?php	}	?>   