<script type='text/javascript'>
		jQuery(function() {
			jQuery("#acdnmenu").accordionMenu();
		});
</script>

<div class="configure-site-div">
<div class="confi-menu">
	<ul>
    	<li><a href="#" class="selected"><div class="confige-sprite site-config-icon-selected"></div><p>Site Configuration</p></a></li>
        <li><a href="<?php echo BASE_URL; ?>configuresite/managemenu"><div class="confige-sprite manage-icon"></div><p>Manage Menu</p></a></li>
        <li><a href="<?php echo BASE_URL; ?>configuresite/sitepreferences"><div class="confige-sprite prefi-icon"></div><p>Site preferences</p></a></li>
    </ul>
</div>
<div class="confi-block-1">
<div class="confi-total-detail">
<div class="confi-body">
   <div id="menu">
            <nav>
            <div id="acdnmenu">
            <ul>
				<li>Date &amp; Time
					<ul>
						<li><a href="#">Link 1</a></li>
						<li class="active"><a href="#">Link 2</a></li>
						<li><a href="#">Link 3</a></li>
					</ul>
				</li>
				<li>Sub Menu
					<ul>
						<li><a href="#">Link 1</a> </li>
						<li><a href="#">Link 2</a> </li>
						<li><a href="#">Link 3</a> </li>
						<li><a href="#">Link 4</a> </li><li><a href="#">Link 5</a> </li><li><a href="#">Link 6</a> </li>
					</ul>
				</li>
            <li><a href="#">Normal Link 1</a></li>
            <li><a href="#">Normal Link 2</a></li>
            </ul>
            </div>
            </nav>
 	</div>
    
    <div class="config-form">
  		<div class="form-body">
        	<div class="form-body-header">Time Format</div>
            <div class="form-content">
             Form Content load here
            </div>        
        </div>  
    </div>                        
    </div>
</div>
</div>